version: '3'

services:
  db:
    container_name: mysql
    image: mysql:8.0.23
    environment:
      TZ: 'Europe/Warsaw'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'nest'
      MYSQL_PASSWORD: 'nest'
      MYSQL_DATABASE: 'nestjs-ddd'
    ports:
      - 3306:3306
    networks:
      - webnet

networks:
  webnet:
